# Generated by Django 3.2.8 on 2021-11-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ('nome',)},
        ),
    ]
